### ISSUE TITLE
Setup new hidpi XFCE environment

### ISSUE THREAD

**Issue by drwonky** [drwonky/drwonky.github.io#1]
- Install Clearlooks-Phenix
- Settings->Appearance->Style choose Clearlooks-Phenix
- Fonts -> set custom DPI setting to 150
- Settings->Window Manager->Style choose Default-hdpi
- Create .config/gtk-3.0/gtk.css:
``` css
scrollbar, scrollbar button, scrollbar slider {
    -GtkScrollbar-has-backward-stepper: true;
    -GtkScrollbar-has-forward-stepper: true;
    min-width: 20px;
    min-height: 20px;
    border-radius: 0;
}

window.background > decoration {
    border: 8px solid #444444;
    background: #444444;
}

window.popup > decoration {
border: none;
}

.titlebar, .titlebar separator, headerbar separator {
    background: #444444;
}

headerbar > box, headerbar > label, headerbar > button grid {
  color:white;
  background: #444444;
}

headerbar button:hover grid, headerbar button:focus grid {
    color:black;
    background: white;
}
```
- Firefox set **layout.css.devPixelsPerPx** to 1.5
